### ISSUE TITLE
Error 500 at first connection

### ISSUE THREAD

**Issue by davidchezmoa** [ZaneH/FireTVRemote-Node#12]
Hi, I setup a new container Debian12 and install npm, clone the repo, and finally I got this issue

root@debian:~/firetv-remote# npm run start

> firetv-remote@0.1.0 start
> node ./bin/www

GET / 500 65.418 ms - 1390
ReferenceError: /root/firetv-remote/views/error.jade:4
    2| 
    3| block content
  > 4|   h1= message
    5|   h2= error.status
    6|   pre #{error.stack}
    7| 

title is not defined
    at eval (eval at exports.compile (/root/firetv-remote/node_modules/jade/lib/jade.js:171:8), <anonymous>:18:58)
    at /root/firetv-remote/node_modules/jade/lib/jade.js:172:35
    at exports.render (/root/firetv-remote/node_modules/jade/lib/jade.js:206:14)
    at exports.renderFile [as engine] (/root/firetv-remote/node_modules/jade/lib/jade.js:233:13)
    at View.render (/root/firetv-remote/node_modules/express/lib/view.js:135:8)
    at tryRender (/root/firetv-remote/node_modules/express/lib/application.js:657:10)
    at Function.render (/root/firetv-remote/node_modules/express/lib/application.js:609:3)
    at ServerResponse.render (/root/firetv-remote/node_modules/express/lib/response.js:1049:7)
    at /root/firetv-remote/app.js:53:7
    at Layer.handle_error (/root/firetv-remote/node_modules/express/lib/router/layer.js:71:5)

**Comment by davidchezmoa** [comment]
I finally did another container with ubuntu 22.04, and I got the remote to start
